---
gems:
- jekyll-archives
- jekyll-sitemap
- jekyll-paginate
exclude:
- "/vendor/"
title: 꼼꼼하게 채워나가는 개발자 노트
subtitle: Hyunni note
email: zzxx9775@gmail.com
name: Changhyun Song
description: 'Developer Hyunni.'
baseurl: ''
url: https://Changhyun-song.github.io
plugins_dir:
- jekyll-sitemap
cover: "/assets/backgroundpic.png"
logo: "/assets/logopic.jpeg"
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true
highlightjs_theme: monokai-sublime
jekyll-archives:
  enabled:
  - categories
  - tags
  layout: archive
  comments: true
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"
disqus_shortname: Changhyun-song
ga_tracking_id: UA-83878761-1
descriptions:
- cat: jekyll
  desc: Posts describing Jekyll setup techniques.
social:
- name: GitHub
  icon: github
  username: Changhyun-song
  url: https://github.com/Changhyun-song
  desc: Fork me on GitHub
  share: false
protocols:
  fb_image: "/assets/logopic.jpg"
  fb_image_width: 612
  fb_image_height: 605
  fb_image_type: image/png
  twitter_image: "/assets/logopic.jpg"
  os_repo: https://github.com/bencentra/centrarium.com
  os_rcs_type: git
  os_src: git@github.com:bencentra/centrarium.com.git
